ViewForApi/Models/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewForApi.Models
{
    public class Address
    {
        public int ID { get; set; }
        public int? CustomerID { get; set; }
        public string Street { get; set; }
        public string CityTown { get; set; }
        public string County { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
    }
}

ViewForApi/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewForApi.Models
{
    public class Customer
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public IList<Address> Addresses { get; set; } = new List<Address>();

    }
}

ViewForApi/Models/ErrorViewModel.cs
using System;

namespace ViewForApi.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewForApi/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewForApi.Models
{
    public class Order
    {

        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string CreatedDate { get; set; }
        public string PaymentPaidDate { get; set; }
        public string DispatchedDate { get; set; }
        public IList<OrderLine> OrderLines { get; set; } = new List<OrderLine>();
        public Customer Customers { get; set; }

    }
}

ViewForApi/Models/OrderLine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewForApi.Models
{
    public class OrderLine
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public Product Product { get; set; }

    }
}

ViewForApi/Models/OrderReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewForApi.Models
{
    public class OrderReport
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public IList<Order> Orders { get; set; } = new List<Order>();
    }
}

ViewForApi/Models/OrderTotal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewForApi.Models
{
    public class OrderTotal
    {
        public string CreatedDate { get; set; }
        public IList<OrderLine> OrderLines { get; set; } = new List<OrderLine>();
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal? Price { get; set; }
        public List<decimal?> SubTotal { get; set; }
    }
}

ViewForApi/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewForApi.Models
{
    public class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal? Price { get; set; }
    }
}

ViewForApi/Controllers/CustomerController.cs
using ViewForApi.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace ViewForApi.Controllers
{
    public class CustomerController : Controller
    {
            //Hosted web API REST Service base url  
            string Baseurl = "https://localhost:44396";
            public async Task<ActionResult> Index()
            {

            List<Customer> CustomerInfo = new List<Customer>();

                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //Sending request to find web api REST service resource GetAllCustomers using HttpClient  
                    HttpResponseMessage Response = await client.GetAsync("api/Customers");

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (Response.IsSuccessStatusCode)
                    {
                        //Storing the response details recieved from web api   
                        var CustomerResponse = Response.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Customer list  
                    CustomerInfo = JsonConvert.DeserializeObject<List<Customer>>(CustomerResponse);

                    }
                    //returning the customer list to view  
                    return View(CustomerInfo);
                }
    }
}
    }

ViewForApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ViewForApi.Models;

namespace ViewForApi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ViewForApi/Controllers/OrderController.cs
using ViewForApi.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ViewForApi.Controllers
{
    public class OrderController : Controller
    {
        string Baseurl = "https://localhost:44396";
        public async Task<ActionResult> Index()
        {

            List<OrderTotal> OrderInfo = new List<OrderTotal>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllCustomers using HttpClient  
                HttpResponseMessage Response = await client.GetAsync("api/OrdersReport");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var OrderResponse = Response.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the OrderInfo list  
                    OrderInfo = JsonConvert.DeserializeObject<List<OrderTotal>>(OrderResponse);
                }
                //returning the OrderInfo list to view  
                return View(OrderInfo);
            }
        }
    }
}

ViewForApi/Views/Customer/Index.cshtml
@model IEnumerable<ViewForApi.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

    <h1>Customer Information</h1>

<table class="table">
    <thead>
        <tr>

            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Email Address
            </th>
            <th>
                Address
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailAddress)
                </td>
                <td>
                    @*----------------------------------------------------------------*@
                    @foreach (var address in item.Addresses)
                    {
                        <p><b>Street:   </b> @Html.DisplayFor(modelItem => address.Street)</p>
                        <p><b>City/Town:    </b> @Html.DisplayFor(modelItem => address.CityTown)</p>
                        <p><b>County:   </b> @Html.DisplayFor(modelItem => address.County)</p>
                        <p><b>PostalCode:   </b> @Html.DisplayFor(modelItem => address.PostalCode)</p>
                        <p><b>Country:  </b> @Html.DisplayFor(modelItem => address.Country)</p>
                    }
                </tr>
            }
    </tbody>
</table>

ViewForApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ViewForApi/Views/Order/Index.cshtml
@model IEnumerable<ViewForApi.Models.OrderTotal>

@{
    ViewData["Title"] = "Index";
}


<h1>Customer Orders</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Order Created
            </th>
            <th>
                Order Total
            </th>
            <th>
                Item
            </th>
            <th>
                Sub-Total
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(model => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(model => item.LastName)
            </td>
            <td>
                <p>@Html.DisplayFor(modelItem => item.CreatedDate)</p>
            </td>
            <td>
                <p><b>£@Html.DisplayFor(modelItem => item.Price)</b></p>
            </td>
            <td>
                @foreach (var lines in item.OrderLines)
                {
                    <p>@Html.DisplayFor(modelItem => lines.Product.Name)</p>
                }
            </td>
            <td>
                @foreach (var lines in item.SubTotal)
                {
                    <p><b>£@Html.DisplayFor(modelItem => lines.Value)</b></p>
                }
            </td>
        </tr>
        }
    </tbody>
</table>

ViewForApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ViewForApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ViewForApi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer Report</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders Report</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ViewForApi - J32951<a asp-area="" asp-controller="Home" asp-action="Index"> Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>